
PRINT '--- AQP_Lab: Setup / IQP toggles / Data ---';
SET NOCOUNT ON;

USE master;
IF DB_ID('AQP_Lab') IS NULL
BEGIN
  PRINT 'Creating database AQP_Lab...';
  EXEC('CREATE DATABASE AQP_Lab');
END
GO

ALTER DATABASE AQP_Lab SET COMPATIBILITY_LEVEL = 160;   -- SQL 2022
GO

ALTER DATABASE AQP_Lab SET QUERY_STORE = ON;
ALTER DATABASE AQP_Lab SET QUERY_STORE (OPERATION_MODE = READ_WRITE, QUERY_CAPTURE_MODE = AUTO);
GO

USE AQP_Lab;
-- Jawne włączenie dźwigni IQP/AQP
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SENSITIVE_PLAN_OPTIMIZATION = ON;  -- PSP
ALTER DATABASE SCOPED CONFIGURATION SET CE_FEEDBACK = ON;                            -- Cardinality Estimation feedback
ALTER DATABASE SCOPED CONFIGURATION SET MEMORY_GRANT_FEEDBACK_PERSISTENCE = ON;      -- MGF persistence (2022)
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = ON;
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;                 -- batch mode bez kolumnstore
ALTER DATABASE SCOPED CONFIGURATION SET DOP_FEEDBACK = ON;                           -- Degree of Parallelism feedback
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF = ON;
GO

-- Dane ze skewem: 99% w grupie 1, 1% w grupie 9999
IF OBJECT_ID('dbo.Skew','U') IS NOT NULL DROP TABLE dbo.Skew;
CREATE TABLE dbo.Skew
(
  id       int IDENTITY(1,1) NOT NULL PRIMARY KEY,
  grp      int NOT NULL,
  payload  char(200) NOT NULL DEFAULT REPLICATE('X',200)
);

;WITH N AS (
  SELECT TOP (200000) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS n
  FROM sys.all_objects a CROSS JOIN sys.all_objects b
)
INSERT dbo.Skew(grp)
SELECT CASE WHEN n%100=0 THEN 9999 ELSE 1 END
FROM N;

CREATE INDEX IX_Skew_grp ON dbo.Skew(grp);
GO

PRINT 'Setup complete. Database = AQP_Lab';
