
PRINT '--- Cleanup: DROP DATABASE AQP_Lab ---';
SET NOCOUNT ON;

USE master;
IF DB_ID('AQP_Lab') IS NOT NULL
BEGIN
  ALTER DATABASE AQP_Lab SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
  DROP DATABASE AQP_Lab;
  PRINT 'AQP_Lab dropped.';
END
ELSE
BEGIN
  PRINT 'AQP_Lab does not exist.';
END
