
-- 00-prereq.sql
-- Tworzy bazę demo i włącza Query Store (READ_WRITE)

IF DB_ID('PSP_Demo') IS NOT NULL
BEGIN
    ALTER DATABASE PSP_Demo SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE PSP_Demo;
END
GO

CREATE DATABASE PSP_Demo;
GO

ALTER DATABASE PSP_Demo SET READ_COMMITTED_SNAPSHOT ON;
GO

ALTER DATABASE PSP_Demo SET QUERY_STORE = ON;
ALTER DATABASE PSP_Demo SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30));
GO
