USE tempdb;
GO
IF OBJECT_ID('dbo.DemoLocks') IS NOT NULL DROP TABLE dbo.DemoLocks;
GO
CREATE TABLE dbo.DemoLocks
(
    id INT IDENTITY(1,1) PRIMARY KEY,
    filler CHAR(100) NOT NULL DEFAULT REPLICATE('X',100)
);
GO
INSERT INTO dbo.DemoLocks DEFAULT VALUES
GO 10000
