
-- 00-create-db.sql
IF DB_ID('ARIES_Demo') IS NOT NULL
BEGIN
    ALTER DATABASE ARIES_Demo SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE ARIES_Demo;
END
GO
CREATE DATABASE ARIES_Demo;
GO
USE ARIES_Demo;
GO
CREATE TABLE dbo.LogDemo(
    ID INT IDENTITY PRIMARY KEY,
    Info NVARCHAR(100),
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);
PRINT 'Database ARIES_Demo created.';
