-- scripts/01_setup.sql
USE master;
IF DB_ID(N'VLF_Lab') IS NOT NULL
BEGIN
    ALTER DATABASE VLF_Lab SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE VLF_Lab;
END;
GO

CREATE DATABASE VLF_Lab
ON PRIMARY
( NAME = N'VLF_Lab', FILENAME = 'C:\SQLData\VLF_Lab.mdf', SIZE = 128MB, FILEGROWTH = 64MB )
LOG ON
( NAME = N'VLF_Lab_log', FILENAME = 'C:\SQLData\VLF_Lab_log.ldf', SIZE = 8MB, FILEGROWTH = 1MB ); -- CELOWO ZŁE
GO

ALTER DATABASE VLF_Lab SET RECOVERY FULL;
GO

USE VLF_Lab;
GO

CREATE TABLE dbo.BigTxn (id INT IDENTITY(1,1) PRIMARY KEY, c CHAR(8000) NOT NULL DEFAULT REPLICATE('Y',8000));
GO
