#!/usr/bin/env python3
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "docs" / "DBA-LIBRARY-INVENTORY.md"

SOURCES = [
    ("standards", "*/README.md", "STANDARD"),
    ("monitoring", "*/README.md", "MONITORING"),
    ("troubleshooting", "*/README.md", "TROUBLESHOOTING"),
    ("runbooks", "*/README.md", "RUNBOOK"),
    ("architecture/adr", "ADR-*.md", "ADR"),
    ("architecture/reference", "*.md", "REFERENCE ARCHITECTURE"),
]

def display_name(path: Path, artifact_type: str) -> str:
    if artifact_type in {"STANDARD", "MONITORING", "TROUBLESHOOTING", "RUNBOOK"}:
        value = path.parent.name
    else:
        value = path.stem
    return value.replace("-", " ").replace("_", " ").strip().title()

rows = []
for root_name, pattern, artifact_type in SOURCES:
    base = ROOT / root_name
    for path in sorted(base.glob(pattern)):
        rows.append({
            "domain": path.parent.name.replace("-", " ").title(),
            "artifact": display_name(path, artifact_type),
            "type": artifact_type,
            "status": "ACTIVE",
            "path": path.relative_to(ROOT).as_posix(),
        })

lines = [
    "# DBA Library Inventory",
    "",
    "> Generated by `tools/dba-library-quality/generate_inventory.py`. Do not edit rows manually.",
    "",
    f"Artifacts: **{len(rows)}**",
    "",
    "| Domain | Artifact | Type | Status | Path |",
    "|---|---|---|---|---|",
]

for row in rows:
    lines.append(
        f"| {row['domain']} | {row['artifact']} | {row['type']} | "
        f"{row['status']} | `{row['path']}` |"
    )

lines += [
    "",
    "## Governance",
    "",
    "- Canonical operational layers are Standards, Monitoring, Troubleshooting, Runbooks and Architecture.",
    "- Artifacts in this inventory are ACTIVE by definition of the canonical layer.",
    "- REFERENCE/LAB/LEGACY content outside these layers is classified incrementally in the cleanup index.",
    "- Regenerate this file after adding, removing or renaming canonical artifacts.",
    "",
]

generated = "\n".join(lines)

if "--check" in sys.argv:
    current = OUTPUT.read_text(encoding="utf-8-sig") if OUTPUT.exists() else ""
    if current != generated:
        print("DBA Library inventory is out of date.")
        print("Run: python tools/dba-library-quality/generate_inventory.py")
        sys.exit(1)
    print("DBA Library inventory is up to date.")
else:
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {len(rows)} artifacts.")
