#!/usr/bin/env python3
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "docs" / "DBA-LIBRARY-INVENTORY.md"

STATUS_RE = re.compile(r"> \*\*Content status:\*\*\s*([^\s]+)")
CANON_RE = re.compile(r"> \*\*Canonical entry point:\*\*\s*(.+)")
REVIEW_RE = re.compile(r"> \*\*Last reviewed:\*\*\s*(.+)")

def title(path: Path, text: str):
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem

def entry(path: Path, artifact_type: str, default_status="ACTIVE"):
    text = path.read_text(encoding="utf-8-sig")
    status = STATUS_RE.search(text)
    canonical = CANON_RE.search(text)
    reviewed = REVIEW_RE.search(text)
    return {
        "domain": path.parent.name,
        "artifact": title(path, text).replace("|", "\\|"),
        "type": artifact_type,
        "status": status.group(1) if status else default_status,
        "canonical": canonical.group(1).strip().replace("|", "\\|") if canonical else "self",
        "reviewed": reviewed.group(1).strip().replace("|", "\\|") if reviewed else "—",
        "path": path.relative_to(ROOT).as_posix(),
    }

rows=[]

for p in sorted((ROOT/"standards").glob("*/README.md")):
    rows.append(entry(p,"STANDARD"))
for p in sorted((ROOT/"monitoring").glob("*/README.md")):
    rows.append(entry(p,"MONITORING"))
for p in sorted((ROOT/"troubleshooting").glob("*/README.md")):
    rows.append(entry(p,"TROUBLESHOOTING"))
for d in sorted(p for p in (ROOT/"runbooks").iterdir() if p.is_dir()):
    p=d/"README.md"
    if p.exists():
        rows.append(entry(p,"RUNBOOK"))
for p in sorted((ROOT/"architecture"/"adr").glob("ADR-*.md")):
    rows.append(entry(p,"ADR"))
for p in sorted((ROOT/"architecture"/"reference").glob("*.md")):
    rows.append(entry(p,"REFERENCE ARCHITECTURE"))

lines=[
    "# DBA Library Inventory",
    "",
    "> Generated by `tools/dba-library-quality/generate_inventory.py`. Do not edit rows manually.",
    "",
    f"Artifacts: **{len(rows)}**",
    "",
    "| Domain | Artifact | Type | Status | Canonical entry | Last reviewed | Path |",
    "|---|---|---|---|---|---|---|",
]
for r in rows:
    lines.append(
        f"| {r['domain']} | {r['artifact']} | {r['type']} | {r['status']} | "
        f"{r['canonical']} | {r['reviewed']} | `{r['path']}` |"
    )
lines += [
    "",
    "## Governance",
    "",
    "- Canonical operational layers are Standards, Monitoring, Troubleshooting, Runbooks and Architecture.",
    "- REFERENCE/LAB/LEGACY content outside these layers is classified incrementally.",
    "- Regenerate this file after adding, removing or renaming canonical artifacts.",
    "",
]
generated="\n".join(lines)

if "--check" in sys.argv:
    current = OUTPUT.read_text(encoding="utf-8-sig") if OUTPUT.exists() else ""
    if current != generated:
        print("DBA Library inventory is out of date.")
        print("Run: python tools/dba-library-quality/generate_inventory.py")
        sys.exit(1)
    print("DBA Library inventory is up to date.")
else:
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {len(rows)} artifacts.")
