-- scripts/01_setup.sql
USE master;
IF DB_ID('QSH_Lab') IS NOT NULL BEGIN ALTER DATABASE QSH_Lab SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE QSH_Lab; END;
GO
CREATE DATABASE QSH_Lab;
ALTER DATABASE QSH_Lab SET COMPATIBILITY_LEVEL = 160;
GO
ALTER DATABASE QSH_Lab SET QUERY_STORE = ON;
ALTER DATABASE QSH_Lab SET QUERY_STORE (OPERATION_MODE = READ_WRITE, QUERY_CAPTURE_MODE = AUTO, INTERVAL_LENGTH_MINUTES = 1);
GO

USE QSH_Lab;
GO
CREATE TABLE dbo.FactBig
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Cat INT NOT NULL,
    Val BIGINT NOT NULL,
    Pad CHAR(400) NOT NULL DEFAULT REPLICATE('H',400)
);
-- Skew + dużo danych
INSERT dbo.FactBig (Cat, Val)
SELECT TOP (800000)
       CASE WHEN (ROW_NUMBER() OVER (ORDER BY (SELECT NULL))) % 5 = 0 THEN 2 ELSE 1 END,
       ABS(CHECKSUM(NEWID()))
FROM sys.all_objects a CROSS JOIN sys.all_objects b;

CREATE INDEX IX_FactBig_Cat ON dbo.FactBig(Cat);
GO

-- Procedura docelowa
CREATE OR ALTER PROCEDURE dbo.SumByCat @cat INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT SUM(Val) AS totalVal
    FROM dbo.FactBig
    WHERE Cat = @cat;
END
GO
