USE master;
GO
IF DB_ID('DemoVersioning') IS NOT NULL
BEGIN
    ALTER DATABASE DemoVersioning SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE DemoVersioning;
END
GO
CREATE DATABASE DemoVersioning;
GO
ALTER DATABASE DemoVersioning SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE DemoVersioning SET READ_COMMITTED_SNAPSHOT ON;
GO
USE DemoVersioning;
GO
CREATE TABLE dbo.T
(
    id INT IDENTITY(1,1) PRIMARY KEY,
    payload CHAR(200) NOT NULL DEFAULT REPLICATE('Z',200)
);
GO
INSERT INTO dbo.T DEFAULT VALUES
GO 20000
