-- scripts/01_setup.sql
USE master;
-- Sprzątanie starych baz
IF DB_ID(N'ADR_On_DB') IS NOT NULL BEGIN ALTER DATABASE ADR_On_DB SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE ADR_On_DB; END;
IF DB_ID(N'ADR_Off_DB') IS NOT NULL BEGIN ALTER DATABASE ADR_Off_DB SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE ADR_Off_DB; END;
GO

-- Tworzenie baz
CREATE DATABASE ADR_On_DB;
CREATE DATABASE ADR_Off_DB;
GO

-- Włączenie/wyłączenie ADR
ALTER DATABASE ADR_On_DB SET ACCELERATED_DATABASE_RECOVERY = ON;
ALTER DATABASE ADR_Off_DB SET ACCELERATED_DATABASE_RECOVERY = OFF;
GO

-- Ta sama struktura i dane
:SETVAR Rows 300000

USE ADR_On_DB;
GO
CREATE TABLE dbo.T (Id INT IDENTITY(1,1) PRIMARY KEY, Pad CHAR(400) NOT NULL DEFAULT REPLICATE('Z',400));
;WITH n AS (SELECT TOP ($(Rows)) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS rn FROM sys.all_objects a CROSS JOIN sys.all_objects b)
INSERT dbo.T DEFAULT VALUES;
GO

USE ADR_Off_DB;
GO
CREATE TABLE dbo.T (Id INT IDENTITY(1,1) PRIMARY KEY, Pad CHAR(400) NOT NULL DEFAULT REPLICATE('Z',400));
;WITH n AS (SELECT TOP ($(Rows)) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS rn FROM sys.all_objects a CROSS JOIN sys.all_objects b)
INSERT dbo.T DEFAULT VALUES;
GO

-- Metryki startowe
SELECT 'ADR_On_DB' AS dbname, * FROM sys.dm_tran_persistent_version_store_stats WHERE database_id = DB_ID('ADR_On_DB');
SELECT 'ADR_Off_DB' AS dbname, * FROM sys.dm_tran_persistent_version_store_stats WHERE database_id = DB_ID('ADR_Off_DB');
GO
