-- scripts/03_long_txn_rollback_ADR_OFF.sql
USE ADR_Off_DB;
GO
SET NOCOUNT ON;
DECLARE @tStart DATETIME2(3) = SYSUTCDATETIME();

BEGIN TRAN;
    DELETE TOP (200000) FROM dbo.T; -- długa operacja
    WAITFOR DELAY '00:00:02';
ROLLBACK;

DECLARE @tEnd DATETIME2(3) = SYSUTCDATETIME();
SELECT DATEDIFF(ms, @tStart, @tEnd) AS rollback_ms, 'ADR_OFF' AS db;
GO
