-- scripts/01_setup.sql
USE master;
IF DB_ID('QS_Lab') IS NOT NULL BEGIN ALTER DATABASE QS_Lab SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE QS_Lab; END;
GO
CREATE DATABASE QS_Lab;
ALTER DATABASE QS_Lab SET COMPATIBILITY_LEVEL = 160; -- SQL 2022 features ready (jeśli 2022)
GO

-- Włączenie Query Store (agresywne capture w labie)
ALTER DATABASE QS_Lab SET QUERY_STORE = ON;
ALTER DATABASE QS_Lab SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7),
    DATA_FLUSH_INTERVAL_SECONDS = 15, INTERVAL_LENGTH_MINUTES = 1, MAX_STORAGE_SIZE_MB = 500,
    QUERY_CAPTURE_MODE = AUTO);
GO

USE QS_Lab;
GO
CREATE TABLE dbo.SalesSkew
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Region INT NOT NULL, -- 1..100, ale 90% to Region=1
    Payload CHAR(400) NOT NULL DEFAULT REPLICATE('Q',400)
);

-- Skew danych: 90% Region=1, 10% pozostałe
INSERT dbo.SalesSkew (Region) SELECT CASE WHEN x%10=0 THEN (x%100)+1 ELSE 1 END
FROM (
    SELECT TOP (500000) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS x
    FROM sys.all_objects a CROSS JOIN sys.all_objects b
) s;

CREATE INDEX IX_SalesSkew_Region ON dbo.SalesSkew(Region);
GO
