; SQL Server 2022 FCI — pierwszy węzeł
[OPTIONS]
ACTION="InstallFailoverCluster"
IACCEPTSQLSERVERLICENSETERMS="True"
ENU="True"
QUIET="True"
UpdateEnabled="True"

FEATURES=SQLENGINE,REPLICATION,FULLTEXT,DQ
INSTANCENAME="MSSQLSERVER"
INSTANCEID="MSSQLSERVER"

; Zasoby klastra
FAILOVERCLUSTERNETWORKNAME="SQLSRV-FCI"
FAILOVERCLUSTERIPADDRESSES="IPv4;192.168.11.60;Cluster Network 1;255.255.255.0"
FAILOVERCLUSTERDISKS="Cluster Disk 1;Cluster Disk 2"

; Katalogi
INSTALLSQLDATADIR="E:\MSSQL"
SQLUSERDBDIR="E:\MSSQL\Data"
SQLUSERDBLOGDIR="F:\MSSQL\Logs"
SQLBACKUPDIR="E:\MSSQL\Backup"
; (opcjonalnie, tylko jeśli T:\ istnieje na obu)
; SQLTEMPDBDIR="T:\MSSQL"

; Konta usług
SQLSVCACCOUNT="sqlmaniak\gmsa_sql$"
AGTSVCACCOUNT="NT SERVICE\SQLSERVERAGENT"
FTSVCACCOUNT="NT Service\MSSQLFDLauncher"

SQLSVCINSTANTFILEINIT="True"
TCPENABLED="1"
SQLSYSADMINACCOUNTS="sqlmaniak\Administrator"
